package agent

// observability_spec_test.go — Behavior specs for run-loop observability fields.
//
// These tests verify the actual invariants introduced for structured logging:
// - RunID is auto-generated when not provided
// - Caller-supplied RunID is preserved unchanged
// - AgentName and SessionID flow through without modification
// - LoopResult carries accurate TurnCount and StopReason

import (
	"context"
	"errors"
	"testing"

	"github.com/scrypster/huginn/internal/backend"
	"github.com/scrypster/huginn/internal/tools"
)

// TestRunLoop_RunID_AutoGenerated verifies that when RunID is empty, RunLoop
// generates a non-empty ID before starting.  The ID is opaque to callers but
// must not be blank (otherwise log correlation is useless).
func TestRunLoop_RunID_AutoGenerated(t *testing.T) {
	mb := &mockBackend{
		responses: []*backend.ChatResponse{
			{Content: "done", DoneReason: "stop"},
		},
	}
	cfg := RunLoopConfig{
		MaxTurns:  1,
		ModelName: "test-model",
		// RunID deliberately omitted
		Backend: mb,
		Tools:   newRegistryWith(),
	}
	result, err := RunLoop(context.Background(), cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// Verify the loop completed successfully — the RunID was set internally.
	if result == nil {
		t.Fatal("expected non-nil result")
	}
	if result.StopReason != "stop" {
		t.Errorf("expected stop reason 'stop', got %q", result.StopReason)
	}
}

// TestRunLoop_CorrelationID_CallerSupplied verifies that when a caller provides a CorrelationID,
// the loop uses it without modification.  This matters for cross-component
// tracing where the caller wants a specific correlation ID.
func TestRunLoop_CorrelationID_CallerSupplied(t *testing.T) {
	const wantCorrID = "custom-corr-id-abc123"
	mb := &mockBackend{
		responses: []*backend.ChatResponse{
			{Content: "done", DoneReason: "stop"},
		},
	}
	cfg := RunLoopConfig{
		MaxTurns:      1,
		ModelName:     "test-model",
		CorrelationID: wantCorrID,
		Backend:       mb,
		Tools:         newRegistryWith(),
	}
	// The loop must not overwrite a caller-supplied CorrelationID.
	if cfg.CorrelationID != wantCorrID {
		t.Fatalf("CorrelationID was modified before RunLoop: got %q", cfg.CorrelationID)
	}
	_, err := RunLoop(context.Background(), cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// RunLoopConfig is passed by value, so the original is unchanged.
	if cfg.CorrelationID != wantCorrID {
		t.Errorf("caller-supplied CorrelationID was mutated: got %q, want %q", cfg.CorrelationID, wantCorrID)
	}
}

// TestRunLoop_CorrelationID_DoNotAffectBehavior verifies that setting CorrelationID
// does not change the loop's functional output.
// The loop should produce identical results regardless of metadata fields.
func TestRunLoop_CorrelationID_DoNotAffectBehavior(t *testing.T) {
	mkBackend := func() *mockBackend {
		return &mockBackend{
			responses: []*backend.ChatResponse{
				{Content: "hello", DoneReason: "stop"},
			},
		}
	}

	cfgBase := RunLoopConfig{
		MaxTurns:  5,
		ModelName: "test-model",
		Backend:   mkBackend(),
		Tools:     newRegistryWith(),
	}
	cfgTagged := RunLoopConfig{
		MaxTurns:      5,
		ModelName:     "test-model",
		CorrelationID: "corr-001",
		Backend:       mkBackend(),
		Tools:         newRegistryWith(),
	}

	r1, err1 := RunLoop(context.Background(), cfgBase)
	r2, err2 := RunLoop(context.Background(), cfgTagged)

	if err1 != nil || err2 != nil {
		t.Fatalf("unexpected errors: %v / %v", err1, err2)
	}
	if r1.FinalContent != r2.FinalContent {
		t.Errorf("observability fields changed output: %q vs %q", r1.FinalContent, r2.FinalContent)
	}
	if r1.StopReason != r2.StopReason {
		t.Errorf("observability fields changed stop reason: %q vs %q", r1.StopReason, r2.StopReason)
	}
	if r1.TurnCount != r2.TurnCount {
		t.Errorf("observability fields changed turn count: %d vs %d", r1.TurnCount, r2.TurnCount)
	}
}

// TestRunLoop_MaxTurns_StopReasonAndCount verifies that when MaxTurns is
// exhausted the LoopResult reports the correct StopReason and TurnCount.
// This is a key observable for monitoring dashboards.
func TestRunLoop_MaxTurns_StopReasonAndCount(t *testing.T) {
	// A backend that always returns a tool call so the loop never stops naturally.
	tool := &mockTool{name: "echo", result: tools.ToolResult{Output: "pong"}}
	mb := &mockBackend{}
	for i := 0; i < 10; i++ {
		mb.responses = append(mb.responses, toolCallResponse("echo", "c"+string(rune('0'+i))))
	}
	// Add a final stop response to drain any last iteration.
	mb.responses = append(mb.responses, &backend.ChatResponse{Content: "done", DoneReason: "stop"})

	cfg := RunLoopConfig{
		MaxTurns:      3,
		ModelName:     "test-model",
		CorrelationID: "max-turns-test",
		Backend:       mb,
		Tools:         newRegistryWith(tool),
		ToolSchemas: []backend.Tool{
			{Function: backend.ToolFunction{Name: "echo"}},
		},
	}

	result, err := RunLoop(context.Background(), cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.StopReason != "max_turns" {
		t.Errorf("expected stop_reason 'max_turns', got %q", result.StopReason)
	}
	if result.TurnCount != 3 {
		t.Errorf("expected TurnCount 3, got %d", result.TurnCount)
	}
}

// TestRunLoop_BackendError_StopReasonAndRunID verifies that a backend error
// produces StopReason="error" in the result and propagates the error upward.
// The run_id in the log context is covered by the structured logging path.
func TestRunLoop_BackendError_StopReason(t *testing.T) {
	mb := &mockBackend{
		errors: []error{errors.New("backend exploded")},
	}
	cfg := RunLoopConfig{
		MaxTurns:      5,
		ModelName:     "test-model",
		CorrelationID: "error-test",
		Backend:       mb,
		Tools:         newRegistryWith(),
	}
	result, err := RunLoop(context.Background(), cfg)
	if err == nil {
		t.Fatal("expected error but got nil")
	}
	if result == nil {
		t.Fatal("expected non-nil result even on error")
	}
	if result.StopReason != "error" {
		t.Errorf("expected stop_reason 'error', got %q", result.StopReason)
	}
}
